name: Generate Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.STATS_TOKEN }}
          base: activity, community, repositories, metadata
          config_timezone: Europe/Moscow
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_repositories: yes
          plugin_repositories_pinned: |
            tom8hawk/TelegramBridge
            tom8hawk/MapBot
            tom8hawk/prod-25
